# Generated by Django 6.0.3 on 2026-03-23 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('accueil', models.FloatField(default=0.0)),
                ('accueil_max', models.FloatField(default=20.0)),
                ('empathie', models.FloatField(default=0.0)),
                ('empathie_max', models.FloatField(default=20.0)),
                ('resolution', models.FloatField(default=0.0)),
                ('resolution_max', models.FloatField(default=20.0)),
                ('langage', models.FloatField(default=0.0)),
                ('langage_max', models.FloatField(default=15.0)),
                ('conformite', models.FloatField(default=0.0)),
                ('conformite_max', models.FloatField(default=15.0)),
                ('cloture', models.FloatField(default=0.0)),
                ('cloture_max', models.FloatField(default=10.0)),
                ('total', models.FloatField(db_index=True, default=0.0)),
                ('ai_total', models.FloatField(default=0.0)),
                ('scored_by', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual'), ('hybrid', 'Hybrid')], db_index=True, default='ai', max_length=20)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='calls.call')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='users.scoringconfig')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('overall_label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, default='neutral', max_length=20)),
                ('overall_score', models.FloatField(default=0.0)),
                ('segments', models.JSONField(blank=True, default=list, help_text='Per-segment sentiment scores')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='calls.call')),
            ],
            options={
                'verbose_name': 'Sentiment',
                'verbose_name_plural': 'Sentiments',
                'db_table': 'sentiment',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, default='', help_text='Reason for the call')),
                ('actions', models.TextField(blank=True, default='', help_text='Actions taken during the call')),
                ('outcome', models.TextField(blank=True, default='', help_text='Call outcome')),
                ('recommendations', models.TextField(blank=True, default='', help_text='AI improvement recommendations')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='calls.call')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
                'db_table': 'summary',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of {label, score} dicts')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='calls.call')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language_detected', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('word_error_rate', models.FloatField(default=0.0)),
                ('duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('segments', models.JSONField(blank=True, default=list, help_text='List of {start, end, speaker, text} dicts')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='calls.call')),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
                'db_table': 'transcript',
            },
        ),
        migrations.CreateModel(
            name='QAReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score_override', models.FloatField(blank=True, null=True)),
                ('original_ai_score', models.FloatField(blank=True, null=True)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa_review', to='calls.call')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QA Review',
                'verbose_name_plural': 'QA Reviews',
                'db_table': 'qa_review',
                'indexes': [models.Index(fields=['status', 'reviewed_at'], name='qa_review_status_fb37f2_idx')],
            },
        ),
    ]
