# Generated by Django 6.0.3 on 2026-03-23 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_phone', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('language', models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('ar', 'Arabic')], db_index=True, default='fr', max_length=5)),
                ('channel', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, default='inbound', max_length=10)),
                ('file_format', models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3'), ('m4a', 'M4A'), ('flac', 'FLAC'), ('ogg', 'OGG')], max_length=10)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('resolution_status', models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('escalated', 'Escalated')], db_index=True, default='unresolved', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='users.agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='users.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'db_table': 'call',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('s3_key', models.CharField(max_length=512, unique=True)),
                ('s3_url', models.TextField()),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('file_size', models.IntegerField(default=0)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_file', to='calls.call')),
            ],
            options={
                'verbose_name': 'Audio File',
                'verbose_name_plural': 'Audio Files',
                'db_table': 'audio_file',
            },
        ),
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('current_step', models.CharField(blank=True, choices=[('transcription', 'Transcription'), ('sentiment', 'Sentiment'), ('topics', 'Topics'), ('scoring', 'Scoring'), ('summary', 'Summary')], db_index=True, max_length=20, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_job', to='calls.call')),
            ],
            options={
                'verbose_name': 'Pipeline Job',
                'verbose_name_plural': 'Pipeline Jobs',
                'db_table': 'pipeline_job',
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['company', 'status'], name='call_company_0f16b8_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['company', 'agent'], name='call_company_aeb0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['company', 'uploaded_at'], name='call_company_a83d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['company', 'is_flagged'], name='call_company_6dbad2_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinejob',
            index=models.Index(fields=['status', 'current_step'], name='pipeline_jo_status_15c51e_idx'),
        ),
    ]
