export const mockAgents = [
  {
    id: 1,
    name: 'Maya Chen',
    email: 'maya.chen@callsight.ai',
    role: 'agent',
    calls: 142,
    average_score: 92,
    average_sentiment: 'positive',
    performance: 'Excellent',
  },
  {
    id: 2,
    name: 'Omar Idrissi',
    email: 'omar.idrissi@callsight.ai',
    role: 'agent',
    calls: 118,
    average_score: 86,
    average_sentiment: 'positive',
    performance: 'Strong',
  },
  {
    id: 3,
    name: 'Leah Martin',
    email: 'leah.martin@callsight.ai',
    role: 'agent',
    calls: 97,
    average_score: 78,
    average_sentiment: 'neutral',
    performance: 'Coaching',
  },
  {
    id: 4,
    name: 'Sam Rivera',
    email: 'sam.rivera@callsight.ai',
    role: 'agent',
    calls: 76,
    average_score: 71,
    average_sentiment: 'neutral',
    performance: 'Watchlist',
  },
];

export const mockCalls = [
  {
    id: 'CALL-1048',
    title: 'Billing dispute resolution',
    agent_name: 'Maya Chen',
    customer_name: 'Avery Stone',
    duration: 512,
    status: 'analyzed',
    sentiment: 'positive',
    quality_score: 94,
    created_at: '2026-05-02T14:30:00Z',
    topics: ['Billing', 'Refund', 'Retention'],
    transcript:
      'Agent: Thank you for calling. I can absolutely help with the unexpected billing charge. Customer: I was charged twice this month. Agent: I understand why that is frustrating. I have reviewed the account and submitted the refund while keeping your service active.',
    summary:
      'The agent acknowledged the duplicate charge, confirmed account details, issued a refund, and retained the customer with clear next steps.',
    coaching_notes:
      'Excellent empathy and ownership. Keep shortening hold-time narration between account checks.',
    audio_url: '',
    scores: {
      greeting_quality: 95,
      empathy: 96,
      problem_resolution: 93,
      professional_language: 94,
      compliance: 92,
    },
  },
  {
    id: 'CALL-1047',
    title: 'Plan downgrade request',
    agent_name: 'Omar Idrissi',
    customer_name: 'Jordan Lee',
    duration: 438,
    status: 'analyzed',
    sentiment: 'neutral',
    quality_score: 82,
    created_at: '2026-05-02T12:05:00Z',
    topics: ['Plan Change', 'Pricing'],
    transcript:
      'Customer requested a lower plan due to budget constraints. Agent reviewed usage, explained tradeoffs, and completed the downgrade after confirmation.',
    summary: 'The call ended with a completed downgrade and no unresolved action items.',
    coaching_notes: 'Good policy clarity. Add one more retention discovery question before processing the downgrade.',
    scores: {
      greeting_quality: 82,
      empathy: 78,
      problem_resolution: 88,
      professional_language: 84,
      compliance: 80,
    },
  },
  {
    id: 'CALL-1046',
    title: 'Technical support escalation',
    agent_name: 'Leah Martin',
    customer_name: 'Morgan Patel',
    duration: 689,
    status: 'processing',
    sentiment: 'negative',
    quality_score: 68,
    created_at: '2026-05-01T17:42:00Z',
    topics: ['Technical Support', 'Escalation'],
    transcript: 'Transcript will appear after analysis completes.',
    summary: 'Analysis is still running for this call.',
    coaching_notes: 'Pending analysis.',
    scores: {
      greeting_quality: 74,
      empathy: 62,
      problem_resolution: 65,
      professional_language: 76,
      compliance: 68,
    },
  },
  {
    id: 'CALL-1045',
    title: 'New subscription onboarding',
    agent_name: 'Sam Rivera',
    customer_name: 'Taylor Brooks',
    duration: 356,
    status: 'pending',
    sentiment: 'neutral',
    quality_score: null,
    created_at: '2026-05-01T09:18:00Z',
    topics: ['Onboarding', 'Subscription'],
    transcript: 'Queued for transcription.',
    summary: 'Queued for AI analysis.',
    coaching_notes: 'Pending analysis.',
    scores: {},
  },
  {
    id: 'CALL-1044',
    title: 'Cancellation save attempt',
    agent_name: 'Maya Chen',
    customer_name: 'Riley Quinn',
    duration: 604,
    status: 'analyzed',
    sentiment: 'negative',
    quality_score: 73,
    created_at: '2026-04-30T16:15:00Z',
    topics: ['Cancellation', 'Retention', 'Product Fit'],
    transcript:
      'Customer wanted to cancel after repeated product fit concerns. Agent listened, offered alternatives, and documented the final cancellation request.',
    summary:
      'The customer still cancelled, but the agent preserved a professional tone and documented the account clearly.',
    coaching_notes: 'Probe earlier for product-fit objections and summarize value before offering concessions.',
    scores: {
      greeting_quality: 81,
      empathy: 75,
      problem_resolution: 66,
      professional_language: 84,
      compliance: 72,
    },
  },
];

export const mockDashboard = {
  kpis: {
    total_calls: 1248,
    analyzed_calls: 1134,
    average_score: 84,
    average_sentiment: 'positive',
    active_agents: 32,
    pending_calls: 27,
  },
  volumeTrend: [
    { date: 'Apr 27', calls: 118, analyzed: 106 },
    { date: 'Apr 28', calls: 132, analyzed: 121 },
    { date: 'Apr 29', calls: 126, analyzed: 118 },
    { date: 'Apr 30', calls: 154, analyzed: 143 },
    { date: 'May 1', calls: 141, analyzed: 129 },
    { date: 'May 2', calls: 167, analyzed: 151 },
    { date: 'May 3', calls: 92, analyzed: 74 },
  ],
  scoreTrend: [
    { date: 'Apr 27', score: 79 },
    { date: 'Apr 28', score: 81 },
    { date: 'Apr 29', score: 83 },
    { date: 'Apr 30', score: 82 },
    { date: 'May 1', score: 85 },
    { date: 'May 2', score: 87 },
    { date: 'May 3', score: 84 },
  ],
  sentimentDistribution: [
    { name: 'Positive', value: 58 },
    { name: 'Neutral', value: 29 },
    { name: 'Negative', value: 13 },
  ],
  topicFrequency: [
    { topic: 'Billing', count: 164 },
    { topic: 'Technical Support', count: 132 },
    { topic: 'Cancellation', count: 88 },
    { topic: 'Onboarding', count: 76 },
    { topic: 'Refund', count: 63 },
  ],
  complianceRate: [
    { date: 'Apr 27', rate: 91 },
    { date: 'Apr 28', rate: 93 },
    { date: 'Apr 29', rate: 92 },
    { date: 'Apr 30', rate: 95 },
    { date: 'May 1', rate: 94 },
    { date: 'May 2', rate: 96 },
    { date: 'May 3', rate: 94 },
  ],
};

export const mockReports = [
  { id: 1, name: 'Weekly Quality Summary', type: 'Quality', status: 'ready', created_at: '2026-05-02T18:00:00Z' },
  { id: 2, name: 'Agent Coaching Pack', type: 'Agent', status: 'ready', created_at: '2026-05-01T18:00:00Z' },
  { id: 3, name: 'Sentiment Risk Review', type: 'Sentiment', status: 'generating', created_at: '2026-05-03T08:30:00Z' },
];
